### PR TITLE
Tutorial Colab notebook

### PR DESCRIPTION
**Pull request by AdityaKane2001**
[Link](https://github.com/AdityaKane2001/regnety/blob/temp_notebook/RegNetY_models_in_TF_2_5.ipynb) to notebook in case not visible in diff.

### CODE REVIEW

**Comment by sayakpaul** [comment]
@AdityaKane2001 could you install [ReviewNB](https://www.reviewnb.com/) in this repository so that it's easier to review the notebook?

**Comment by sayakpaul** [comment]
Thanks @AdityaKane2001. ReviewNB is acting up weird lately. I have commented there and have also recorded a screencast of my comments [here](https://www.loom.com/share/aaadb6aa4b344da6bd3589d0b46862e8).

**Comment by AdityaKane2001** [comment]
@sayakpaul 

Made requested changes in the notebook.

**Review by sayakpaul — APPROVED** [review]
Let @MorganR review as well.

**Comment by AdityaKane2001** [comment]
@MorganR 

Could you please take a look at this?

**Comment by MorganR** [comment]
Looks good! Just suggested a few small changes

**Comment by AdityaKane2001** [comment]
@MorganR 

Made requested changes except validation augmentations one.

**Comment by AdityaKane2001** [comment]
@MorganR 

If the notebook is good to go, please approve the PR. I'll merge this to main and add the links in the TFHub PR.

**Comment by sayakpaul** [comment]
> It still seems unusual to crop the validation images, but as long as it's a static change I don't see an issue with it.

@MorganR central crops during inference, validation, evaluation in image classification is a widely adopted preprocessing scheme.

**Review by MorganR — APPROVED** [review]
Approved pending small change to hub.load

**Comment by AdityaKane2001** [comment]
@sayakpaul @MorganR 

Merging this one. Thank you for the reviews and suggestions.

**Pull request merged**
